// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYd1pNqCb37ik2tc7j8--t-LwH9bJFuiE',
    appId: '1:74696736533:web:30d51944a56798ed31331c',
    messagingSenderId: '74696736533',
    projectId: 'project-uas-ega',
    authDomain: 'project-uas-ega.firebaseapp.com',
    storageBucket: 'project-uas-ega.firebasestorage.app',
    measurementId: 'G-THL9E8FKZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhUTTNAgaNpvSruVbXhgQA-RJ_hetzBHQ',
    appId: '1:74696736533:android:11d9d70b30649ed531331c',
    messagingSenderId: '74696736533',
    projectId: 'project-uas-ega',
    storageBucket: 'project-uas-ega.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHegvF5MA3V-tEL82n3fCiy4NXPFTLiYI',
    appId: '1:74696736533:ios:389edff2f0d5c75a31331c',
    messagingSenderId: '74696736533',
    projectId: 'project-uas-ega',
    storageBucket: 'project-uas-ega.firebasestorage.app',
    iosBundleId: 'com.example.setupUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHegvF5MA3V-tEL82n3fCiy4NXPFTLiYI',
    appId: '1:74696736533:ios:389edff2f0d5c75a31331c',
    messagingSenderId: '74696736533',
    projectId: 'project-uas-ega',
    storageBucket: 'project-uas-ega.firebasestorage.app',
    iosBundleId: 'com.example.setupUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYd1pNqCb37ik2tc7j8--t-LwH9bJFuiE',
    appId: '1:74696736533:web:dee56438276883e831331c',
    messagingSenderId: '74696736533',
    projectId: 'project-uas-ega',
    authDomain: 'project-uas-ega.firebaseapp.com',
    storageBucket: 'project-uas-ega.firebasestorage.app',
    measurementId: 'G-H1447ZRBTS',
  );
}
